# Generated by Django 3.0.2 on 2020-01-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deviceid',
            unique_together={('id_type', 'value')},
        ),
        migrations.AddIndex(
            model_name='deviceid',
            index=models.Index(fields=['id_type', 'value'], name='server_devi_id_type_059f91_idx'),
        ),
    ]
