# Generated by Django 3.0.2 on 2020-01-23 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20200123_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('secret', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('token',)},
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['token'], name='server_devi_token_0c2503_idx'),
        ),
        migrations.AddField(
            model_name='credential',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='server.Device'),
        ),
        migrations.AddIndex(
            model_name='credential',
            index=models.Index(fields=['target', 'user'], name='server_cred_target_94d2be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='credential',
            unique_together={('target', 'user')},
        ),
    ]
