# Generated by Django 3.0.2 on 2020-01-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_log'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='credential',
            name='server_cred_target_94d2be_idx',
        ),
        migrations.AlterUniqueTogether(
            name='credential',
            unique_together={('target', 'user', 'device_id')},
        ),
        migrations.AddIndex(
            model_name='credential',
            index=models.Index(fields=['target', 'user', 'device_id'], name='server_cred_target_c0aa00_idx'),
        ),
    ]
