# Generated by Django 3.0.2 on 2020-01-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20200125_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='secret',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
