# Generated by Django 3.0.2 on 2020-01-28 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20200126_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('api_key', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='device',
            name='server_devi_token_0c2503_idx',
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='token',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='server.App'),
        ),
        migrations.AddField(
            model_name='token',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='server.Device'),
        ),
        migrations.RemoveField(
            model_name='device',
            name='token',
        ),
        migrations.AddField(
            model_name='credential',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials', to='server.App'),
        ),
        migrations.AddField(
            model_name='log',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='server.App'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['device_id', 'app_id'], name='server_toke_device__098c1f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('device_id', 'app_id')},
        ),
    ]
